from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, Sequence

from services.course_management.models import Course, Lesson, PresignResult


class UserProfileProvisioner(Protocol):
    """Minimal surface from ``UserProfileService`` used by course HTTP handlers."""

    def get_or_create_profile(self, *, user_sub: str, email: str, role: str) -> Dict[str, Any]: ...


class CourseCatalogRepositoryPort(Protocol):
    def list_courses(self) -> List[Course]: ...
    def list_courses_by_instructor(self, created_by: str) -> List[Course]: ...
    def get_course(self, course_id: str) -> Optional[Course]: ...
    def create_course(self, title: str, description: str, *, created_by: str = "") -> Course: ...
    def update_course(self, course_id: str, title: str, description: str) -> None: ...
    def set_course_status(self, course_id: str, status: str) -> None: ...

    def list_lessons(self, course_id: str) -> List[Lesson]: ...
    def get_lesson_by_id(self, course_id: str, lesson_id: str) -> Optional[Lesson]: ...
    def create_lesson(self, course_id: str, title: str) -> Lesson: ...
    def update_lesson_title(self, course_id: str, lesson_id: str, title: str) -> None: ...
    def delete_lesson(self, course_id: str, lesson_id: str) -> None: ...
    def delete_course_and_lessons(self, course_id: str) -> None: ...
    def set_lesson_video(self, course_id: str, lesson_id: str, video_key: str, status: str) -> None: ...
    def set_lesson_video_if_video_key_matches(
        self, course_id: str, lesson_id: str, video_key: str, status: str, *, expected_video_key: str
    ) -> None: ...
    def set_lesson_video_status(self, course_id: str, lesson_id: str, status: str) -> None: ...
    def set_lesson_orders(self, course_id: str, orders: Dict[str, int]) -> None: ...
    def set_course_thumbnail(self, course_id: str, thumbnail_key: str) -> None: ...
    def set_lesson_thumbnail(self, course_id: str, lesson_id: str, thumbnail_key: str) -> None: ...


class CourseMediaStoragePort(Protocol):
    def presign_put(
        self,
        *,
        course_id: str,
        lesson_id: str,
        filename: str,
        content_type: str,
        expires_seconds: int = 300,
    ) -> PresignResult: ...
    def presign_thumbnail_put(
        self,
        *,
        course_id: str,
        filename: str,
        content_type: str,
        expires_seconds: int = 300,
    ) -> PresignResult: ...
    def presign_lesson_thumbnail_put(
        self,
        *,
        course_id: str,
        lesson_id: str,
        filename: str,
        content_type: str,
        expires_seconds: int = 300,
    ) -> PresignResult: ...
    def presign_get(self, *, key: str, expires_seconds: int = 3600) -> str: ...
    def delete_object(self, key: str) -> None: ...
    def delete_objects(self, keys: Sequence[str]) -> List[str]: ...

