"""Canonical country and profession lists (Bahaa prototype ``data.js``)."""

from __future__ import annotations

# EXACTLY matches prototype data.js — keep in sync with frontend profile-options (RS-6 Slice C).
PROFESSIONS: tuple[str, ...] = (
    "Medical Student",
    "Resident",
    "Fellow",
    "Physician",
    "Surgeon",
    "Dentist",
    "Pharmacist",
    "Nurse",
    "Allied Health Professional",
    "Researcher",
    "Faculty Member",
    "Healthcare Administrator",
    "Other",
)

COUNTRIES: tuple[str, ...] = (
    "Jordan",
    "Saudi Arabia",
    "United Arab Emirates",
    "Egypt",
    "Kuwait",
    "Qatar",
    "Bahrain",
    "Oman",
    "Lebanon",
    "Iraq",
    "Palestine",
    "Syria",
    "Yemen",
    "Libya",
    "Tunisia",
    "Algeria",
    "Morocco",
    "Sudan",
    "Pakistan",
    "India",
    "Bangladesh",
    "Nigeria",
    "Kenya",
    "Ghana",
    "United Kingdom",
    "United States",
    "Canada",
    "Australia",
    "Germany",
    "France",
    "Netherlands",
    "Sweden",
    "Turkey",
    "Malaysia",
    "Indonesia",
    "Philippines",
    "Other",
)
