/** Canonical lists — keep in sync with `profile_allowlists.py` (RS-6). */

export const PROFESSIONS: readonly string[] = [
  'Medical Student',
  'Resident',
  'Fellow',
  'Physician',
  'Surgeon',
  'Dentist',
  'Pharmacist',
  'Nurse',
  'Allied Health Professional',
  'Researcher',
  'Faculty Member',
  'Healthcare Administrator',
  'Other',
] as const

export const COUNTRIES: readonly string[] = [
  'Jordan',
  'Saudi Arabia',
  'United Arab Emirates',
  'Egypt',
  'Kuwait',
  'Qatar',
  'Bahrain',
  'Oman',
  'Lebanon',
  'Iraq',
  'Palestine',
  'Syria',
  'Yemen',
  'Libya',
  'Tunisia',
  'Algeria',
  'Morocco',
  'Sudan',
  'Pakistan',
  'India',
  'Bangladesh',
  'Nigeria',
  'Kenya',
  'Ghana',
  'United Kingdom',
  'United States',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'Netherlands',
  'Sweden',
  'Turkey',
  'Malaysia',
  'Indonesia',
  'Philippines',
  'Other',
] as const
